### ISSUE TITLE
iperf3 versions not working

### ISSUE THREAD

**Issue by mdawsonuk** [iitggithub/iperf-server#1]
Hi,

It looks like you're calling `iperf` instead of `iperf3` on the Iperf3 images - this means the images aren't running correctly.

**Comment by iitggithub** [comment]
Updated 3.10.1/run.sh and 3.1.3/run.sh to use /usr/bin/iperf3 instead of /usr/bin/iperf.

`[ec2-user@ip-172-31-28-71 ~]$ sudo docker exec -it 8319b5f4e20b /usr/bin/iperf3 -v
iperf 3.1.3
Linux 8319b5f4e20b 4.14.186-146.268.amzn2.x86_64 #1 SMP Tue Jul 14 18:16:52 UTC 2020 x86_64
Optional features available: CPU affinity setting, TCP congestion algorithm setting, sendfile / zerocopy, socket pacing
[ec2-user@ip-172-31-28-71 ~]$ 
[ec2-user@ip-172-31-28-71 ~]$ 
[ec2-user@ip-172-31-28-71 ~]$ sudo docker ps
CONTAINER ID   IMAGE                            COMMAND     CREATED          STATUS          PORTS                NAMES
3b30bd9452aa   iitgdocker/iperf-server:3.10.1   "/run.sh"   15 seconds ago   Up 14 seconds   5001/tcp, 5001/udp   nifty_golick
[ec2-user@ip-172-31-28-71 ~]$ sudo docker exec -it 3b30bd9452aa /usr/bin/iperf3 -v
iperf 3.10.1 (cJSON 1.7.13)
Linux 3b30bd9452aa 4.14.186-146.268.amzn2.x86_64 #1 SMP Tue Jul 14 18:16:52 UTC 2020 x86_64
Optional features available: CPU affinity setting, TCP congestion algorithm setting, sendfile / zerocopy, socket pacing, bind to device, support IPv4 don't fragment
`
Looks like it's working now.
