### ISSUE TITLE
UDP start mode is broken on iperf 3.x

### ISSUE THREAD

**Issue by julianxhokaxhiu** [iitggithub/iperf-server#3]
I'm currently testing your image and I found out the `ARGS` part is redundant because if you specify the `ARGS=-u` argument, iperf v3.x will complain you're using a client side flag.

Just using `iperf3 -s` is enough to enable UDP testing.

Thank you in advance.

**Comment by iitggithub** [comment]
Testing this myself, and by default it starts a tcp server:

`/ # iperf3 -s &
/ # -----------------------------------------------------------
Server listening on 5201 (test #1)
-----------------------------------------------------------

/ # netstat -autnlp
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 :::5201                 :::*                    LISTEN      20/iperf3`

In the documentation for iperf3, I couldn't find any mention as to how to explicitly configure a UDP server but I did read that it magically creates one upon first connection. It's an odd change.

I'll commit a simplified docker-compose-iperf3.yml file since it no longer needs to differentiate between tcp and udp iperf3 servers.

**Comment by iitggithub** [comment]
Removed UDP specific information from docker compose file.
