### ISSUE TITLE
Wrong default port for iperf 3.x

### ISSUE THREAD

**Issue by julianxhokaxhiu** [iitggithub/iperf-server#4]
In your README and examples is stated that the default port is `5001`, while in fact it is `5201`.

You might want to consider fixing it.

Thank you in advance.

**Comment by iitggithub** [comment]
The default port depends on which version of iperf you're using. iperf is 5001, and iperf3 is 5201 as per the documentation.

https://iperf.fr/iperf-doc.php

The example in README.md should be pulling iperf rather than iperf3 making it still accurate. I'll probably break out the existing docker-compose.yml file in the repo into two separate files so it's easier to distinguish between the two.
